apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "theia-template.fullname" . }}
  labels:
    {{- include "theia-template.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .host | quote }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "theia-template.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
              
              

