apiVersion: v1
kind: Service
metadata:
  name: {{ include "theia-template.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "theia-template.selectorLabels" . | nindent 4 }}
